const IMAGES = {
  LOAD: 'IMAGE_LOAD',
  LOAD_SUCCESS: 'IMAGE_LOAD_SUCCESS',
  LOAD_FAIL: 'IMAGE_LOAD_FAILURE'
}

const STATS = {
  LOAD: 'STATS_LOAD',
  LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
  LOAD_FAIL: 'STATS_LOAD_FAILURE'
}

const IMAGE_STATS = {
  LOAD: 'IMAGE_STATS_LOAD',
  LOAD_SUCCESS: 'IMAGE_STATS_LOAD_SUCCESS',
  LOAD_FAIL: 'IMAGE_STATS_LOAD_FAIL'
}

export { 
  IMAGES,
  STATS,
  IMAGE_STATS
}